### ISSUE TITLE
Read the translations folder from framework.translator.paths configuration

### ISSUE THREAD

**Issue by monteiro** [willdurand/BazingaJsTranslationBundle#160]
BazingJsTranslationBundle doesn't look into the **framework.translator.paths** for extra-paths to look for translations.

For example, I want to have my translations in infrastructure/Ui/Translations and my symfony configuration is:

```
framework:
    translator:
        fallback: en
        paths:
            - '%kernel.root_dir%/../src/Infrastructure/Ui/Translations'

```

The file **TranslationFinder** is responsible for looking the translation folder. I have hardcoded the new folder to test and it works:
```
$locations[] = $this->kernel->getRootDir() . '/../src/Infrastructure/Ui/Translations';
```
