### ISSUE TITLE
Redirection to /translations after login

### ISSUE THREAD

**Issue by Glideh** [willdurand/BazingaJsTranslationBundle#167]
I'm randomly getting redirected to `/translations` after successful login.
I don't know how to debug that as I can't reproduce it.
I'm using the version `2.5.0`

**Comment by monteiro** [comment]
@Glideh This is still happening?

**Comment by Glideh** [comment]
Yes I still have it, I found the origin of the issue though.
My firewall has the default `login` configuration
(which redirects to the last request after successful login)

`/translations` is the last resource loaded by my templates throughout my application, so it gets often registered in the session as the "referer".

I don't understand why since it is supposed to be a `XMLHTTPRequest` and (in Symfony 3) [`Symfony\Component\Security\Http\Firewall\ExceptionListener`](https://github.com/symfony/security-http/blob/master/Firewall/ExceptionListener.php#L220) seems to skip them:

```php
protected function setTargetPath(Request $request)
{
    // session isn't required when using HTTP basic authentication mechanism for example
    if ($request->hasSession() && $request->isMethodSafe() && !$request->isXmlHttpRequest()) {
        $this->saveTargetPath($request->getSession(), $this->providerKey, $request->getUri());
    }
}
```

2 solutions/workarounds for me:

* Whitelisting `/translations` from the `access_control` (`security.yml`):
```yml
security:
    access_control:
        - { path: ^/translations, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

or

* Disabling the "referer" target path of login (still in `security.yml`):
```yml
security:
    firewalls:
        main:
            form_login:
                always_use_default_target_path: true
                default_target_path: homepage
```
