### ISSUE TITLE
Redirects to translation file after successful login

### ISSUE THREAD

**Issue by tautvydasr** [willdurand/BazingaJsTranslationBundle#178]
I configured bundle with instructions provided on [documentation](https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/doc/index.md). Everything works fine but after successful login, I get redirected to http://my.domain/translations/ and the content of that file is shown.

I found the similar problem on [stackowerflow](http://stackoverflow.com/questions/23818005/issue-using-willdurand-bazingajstranslationbundle) and there was a security problem. I tried that solution but it didn't work for me.

I changed original script tag `<script src="{{ url('bazinga_jstranslation_js') }}"></script>` with `<script>{{ render(url('bazinga_jstranslation_js')) }}</script>` and that solved my problem.

**Comment by monteiro** [comment]
Hi,

Are you using the latest 2.6 version?

**Comment by tautvydasr** [comment]
Yes, I am using 2.6 version.

**Comment by monteiro** [comment]
@tautvydasr I couldn't simulate the possible bug.

I've used the symfony-demo application and followed the documentation and everything went fine. 
I've installed BazingaJS in the demo app: https://drive.google.com/open?id=0B8mMjv7GynlaQXNSUEYyOFlQYW8

I changed the file: 
- base.html.twig (you can take a look at the code)

I've created an alert with a specific call to a translation to see if it was working and everything seems to be working.

For you to run the symfony app in this zip, you just need to do:

```
unzip symfony-demo.zip
composer install
bin/console assetic:dump; assets:install
bin/console server:run
go to http://127.0.0.1:8000
```

**Comment by tautvydasr** [comment]
I also could not reproduce this bug on demo project. Maybe it is because I am using 2.7.9 Symfony version.

**Comment by monteiro** [comment]
Maybe it is related with your security settings? :( I need more information besides the symfony version to discover the bug :)

**Comment by tautvydasr** [comment]
My security config:
  ```
firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|error)|css|images|js|translations)/
      security: false

    api_version:
      pattern: ^/api/version$
      security: false

    main:
      anonymous: true
      pattern: ^/
      form_login:
        login_path: app_auth_login
        check_path: app_auth_check
        default_target_path: app_dashboard_index
        intention: _app_auth_login
      logout:
        path: app_auth_logout
        target: app_auth_login
      remember_me:
        key: '%remember_me_key%'
        lifetime: 2592000
        path: /

```
